import { useParams } from "react-router-dom";
import { domainDetails } from "../data/domainDetails";
import TopNavbar from "../components/topnav";
import { useState } from "react";
import jsPDF from "jspdf";
import { useNavigate } from "react-router-dom";


export default function DomainDetail() {
    const navigate = useNavigate();

    const { id } = useParams();
    const data = domainDetails[id];

    const [activeTab, setActiveTab] = useState("overview");
    const [filter, setFilter] = useState("all");
    const [expandedLevel, setExpandedLevel] = useState(null);
    const levelStyles = {
        beginner: {
            title: "text-blue-400",
            hoverBorder: "hover:border-blue-400/40",
            hoverShadow: "hover:shadow-[0_0_20px_rgba(59,130,246,0.3)]",
        },
        intermediate: {
            title: "text-purple-400",
            hoverBorder: "hover:border-purple-400/40",
            hoverShadow: "hover:shadow-[0_0_20px_rgba(168,85,247,0.4)]",
        },
        advanced: {
            title: "text-pink-400",
            hoverBorder: "hover:border-pink-400/40",
            hoverShadow: "hover:shadow-[0_0_20px_rgba(236,72,153,0.4)]",
        },
    };

    if (!data) {
        return <div className="text-white p-20">Domain not found.</div>;
    }

    // Filter careers properly
    const filteredCareers =
        filter === "all"
            ? data.careers
            : data.careers.filter((career) => career.type === filter);
    const generateReport = () => {
        const doc = new jsPDF();

        let y = 20;

        // Title
        doc.setFontSize(18);
        doc.setTextColor(20, 40, 90);
        doc.text(`${id.toUpperCase()} Career Report`, 105, y, {
            align: "center",
        });

        y += 15;

        // Overview Section
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text("Overview", 10, y);
        y += 8;

        doc.setFontSize(11);
        doc.text(data.overview, 10, y, { maxWidth: 180 });
        y += 30;

        // Careers Section
        doc.setFontSize(14);
        doc.text("Career Opportunities", 10, y);
        y += 10;

        doc.setFontSize(11);

        data.careers.forEach((career) => {
            doc.text(`• ${career.role}`, 10, y);
            y += 6;

            doc.setTextColor(80);
            doc.text(`${career.demand}`, 14, y);
            doc.setTextColor(0, 0, 0);
            y += 10;
        });

        // Footer
        doc.setFontSize(9);
        doc.setTextColor(150);
        doc.text("Generated by CosmoQuest Learning System", 105, 285, {
            align: "center",
        });

        doc.save(`${id}-career-report.pdf`);
    };

    const getTimeEstimate = (level) => {
        if (level === "beginner") return "6–12 months";
        if (level === "intermediate") return "1–2 years";
        if (level === "advanced") return "2+ years";
    };

    const getFocusArea = (level) => {
        if (level === "beginner") return "Fundamentals & Core Concepts";
        if (level === "intermediate") return "Applied Knowledge & Systems";
        if (level === "advanced") return "Specialization & Research Depth";
    };

    const getProjectSuggestion = (level) => {
        if (level === "beginner") return "Build a basic simulation or small analysis project.";
        if (level === "intermediate") return "Develop a mini research-based or system-level project.";
        if (level === "advanced") return "Contribute to open-source research or publish findings.";
    };


    return (
        <>
            <TopNavbar />
            <div className="min-h-screen bg-[#0B0F1A] text-white px-10 pt-32 pb-20 space-y-10 ">



                <button
                    onClick={() => navigate("/learn")}
                    className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 border border-white/10 hover:border-blue-400/40 hover:bg-white/10 transition-all duration-300 mb-8"
                >
                    <span className="text-lg">←</span>
                    <span>Back to Domains</span>
                </button>
                {/* Domain Header */}
                <div className="mb-12 space-y-6">

                    <div>
                        <h1 className="text-4xl md:text-5xl font-bold tracking-wide bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent font-orbitron">
                            {id.replace("-", " ").toUpperCase()}
                        </h1>

                        <p className="text-gray-400 mt-4 max-w-3xl">
                            {data.overview}
                        </p>
                    </div>

                    {/* Meta Info Cards */}
                    <div className="grid md:grid-cols-3 gap-6">

                        <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                            <p className="text-gray-400 text-sm">Primary Focus</p>
                            <p className="font-semibold capitalize">
                                {data.careers[0]?.type || "Research"}
                            </p>
                        </div>

                        <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                            <p className="text-gray-400 text-sm">Academic Depth</p>
                            <p className="font-semibold">
                                {data.qualifications?.includes("PhD") ? "High (Research-Oriented)" : "Moderate to High"}
                            </p>
                        </div>

                        <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                            <p className="text-gray-400 text-sm">Growth Outlook</p>
                            <p className="font-semibold">
                                {data.industryOutlook?.summary?.includes("growth") ? "Increasing" : "Stable"}
                            </p>
                        </div>

                    </div>

                </div>


                {/* Tabs */}
                <div className="flex gap-6 border-b border-white/10 mb-10">
                    {["overview", "roadmap", "careers", "outlook", "resources"].map((tab) => (
                        <button
                            key={tab}
                            onClick={() => setActiveTab(tab)}
                            className={`pb-3 capitalize transition-all duration-300 ${activeTab === tab
                                ? "border-b-2 border-blue-400 text-white"
                                : "text-gray-400 hover:text-white"
                                }`}
                        >
                            {tab}
                        </button>
                    ))}
                </div>

                {/* Overview */}
                {activeTab === "overview" && (
                    <p className="text-gray-400">{data.overview}</p>
                )}

                {/* Roadmap */}
                {activeTab === "roadmap" && (
                    <div className="grid md:grid-cols-3 gap-6">
                        {["beginner", "intermediate", "advanced"].map((level) => (
                            <div
                                key={level}
                                onClick={() =>
                                    setExpandedLevel(expandedLevel === level ? null : level)
                                }
                                className={`cursor-pointer bg-white/5 backdrop-blur-sm p-6 rounded-xl border border-white/10
${expandedLevel === level ? "bg-white/10 scale-[1.02]" : ""}
${levelStyles[level].hoverBorder}
${levelStyles[level].hoverShadow}
transition-all duration-300`}

                            >
                                <h3
                                    className={`text-lg font-semibold mb-4 capitalize ${levelStyles[level].title}`}
                                >
                                    {level}
                                </h3>

                                <ul className="space-y-2 text-gray-400">
                                    {data.roadmap[level].map((item, i) => (
                                        <li key={i}>• {item}</li>
                                    ))}
                                </ul>

                                {expandedLevel === level && (
                                    <div className="mt-6 pt-4 border-t border-white/10 text-sm text-gray-400 space-y-2">
                                        <p><strong>Estimated Time:</strong> {getTimeEstimate(level)}</p>
                                        <p><strong>Focus:</strong> {getFocusArea(level)}</p>
                                        <p><strong>Suggested Mini Project:</strong> {getProjectSuggestion(level)}</p>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>
                )}


                {/* Careers */}
                {activeTab === "careers" && (
                    <div>
                        <div className="flex justify-between items-center mb-8 flex-wrap gap-4">
                            <div className="flex gap-4">
                                {["all", "research", "engineering", "ai"].map((type) => (
                                    <button
                                        key={type}
                                        onClick={() => setFilter(type)}
                                        className={`px-4 py-2 rounded-lg capitalize transition-all duration-300 ${filter === type
                                            ? "bg-blue-600 text-white"
                                            : "bg-white/10 text-gray-400 hover:bg-white/20"
                                            }`}
                                    >
                                        {type}
                                    </button>
                                ))}
                            </div>

                            <button
                                onClick={generateReport}
                                className="px-6 py-2 rounded-lg bg-gradient-to-r from-blue-600 to-purple-600 hover:scale-105 transition-all duration-300"
                            >
                                Download Report
                            </button>
                        </div>

                        <div className="space-y-6">
                            {filteredCareers.map((career, i) => (
                                <div
                                    key={i}
                                    className="bg-gradient-to-r from-white/5 to-white/0 p-6 rounded-xl border border-white/10 hover:border-blue-400/40 transition-all duration-300"
                                >
                                    <h3 className="font-semibold text-lg">{career.role}</h3>
                                    <p className="text-gray-400">{career.demand}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Outlook */}
                {activeTab === "outlook" && (
                    <div>
                        <p className="text-gray-400 mb-4">
                            {data.industryOutlook.summary}
                        </p>
                    </div>
                )}

                {/* Resources */}
                {activeTab === "resources" && (
                    <div>
                        {data.videos?.map((video, i) => (
                            <a
                                key={i}
                                href={video.link}
                                target="_blank"
                                rel="noreferrer"
                                className="block bg-white/5 p-4 rounded-lg hover:bg-white/10 mb-4"
                            >
                                {video.title}
                            </a>
                        ))}
                    </div>
                )}

            </div>
        </>
    );
}

